Repository nl-design-system/documentatie, pull requests merged in 2024-07, with the labels that each got.

#1108 Description en title Table toegevoegd
  docs/componenten/table/index.mdx
Labels: merged with TODOs

#1133 Description Fieldset toegevoegd.mdx
  docs/componenten/fieldset/index.mdx
Labels: merged with unresolved review

#1140 Description Form field toegevoegd.mdx
  docs/componenten/form-field/index.mdx
Labels: merged with unresolved review

#1128 Description Date input group toegevoegd.mdx
  docs/componenten/date-input-group/index.mdx
Labels: merged with unresolved review

#1114 Description Video toegevoegd
  docs/componenten/video/index.mdx
Labels: merged with unresolved review

#1127 Description Data badge toegevoegd.mdx
  docs/componenten/data-badge/index.mdx
Labels: merged with unresolved review

#1124 Description Calendar toegevoegd.mdx
  docs/componenten/calendar/index.mdx
Labels: merged with unresolved review

#1123 Description Avatar toegevoegd.mdx
  docs/componenten/avatar/index.mdx
Labels: merged with unresolved review

#1116 Description Number input toegevoegd
  docs/componenten/number-input/index.mdx
Labels: merged with unresolved review

#1118 Description Spinner aangepast
  docs/componenten/spinner/index.mdx
Labels: merged with unresolved review

#1134 Description File input toegevoegd.mdx
  docs/componenten/file-input/index.mdx
Labels: merged with unresolved review

#1110 Description Textarea toegevoegd
  docs/componenten/textarea/index.mdx
Labels: merged with unresolved review

#1129 Description Date picker toegevoegd.mdx
  docs/componenten/date-picker/index.mdx
Labels: merged with unresolved review

#1098 Description Password input toegevoegd
  docs/componenten/password-input/index.mdx
Labels: Discussion
